### ISSUE TITLE
Exceptions should inherit from same base class

### ISSUE THREAD

**Issue by svisser** [carlospalol/money#11]
The exception classes in this package currently don't all inherit from the same base class. This makes it difficult to "do some money calculations" and stop whenever an error occurs. For example:

```python
from decimal import Decimal
from money import xrates, Money, XMoney
xrates.install('money.exchange.SimpleBackend')
xrates.base = 'GBP'
xrates.setrate('EUR', Decimal('2'))

# Raises money.exceptions.ExchangeRateNotFound:
price1 = XMoney('3.00', 'GBP') + Money('50.00', 'AUD')

# Raises money.exceptions.CurrencyMismatch:
price2 = Money('3.00', 'GBP') + XMoney('50.00', 'AUD')
```

This means as a developer I basically have to inspect the `money` code to know what exceptions can be raised. I would like to write:

```python
try:
    price1 = XMoney('3.00', 'GBP') + Money('50.00', 'AUD')
    price2 = Money('3.00', 'GBP') + XMoney('50.00', 'AUD')
except (all money exceptions to catch here):
    print("Something went wrong")
```

but I can't because I'd need to know what all those exceptions are. By introducing a base class we can catch and handle everything:

```python
try:
    price1 = XMoney('3.00', 'GBP') + Money('50.00', 'AUD')
    price2 = Money('3.00', 'GBP') + XMoney('50.00', 'AUD')
except MoneyException:
    print("Something went wrong")
```

Also, please don't consider these several issue reports as a bad thing; I'm considering to use this package and I want to make sure we don't run into unexpected issues down the line.

**Comment by carlospalol** [comment]
Thanks for the suggestion.
