### ISSUE TITLE
Make Money hashable?

### ISSUE THREAD

**Issue by dahlia** [carlospalol/money#14]
Although it could be both a question and a proposal at a time, is there any reason why `Money` is unhashable?

```pycon
>>> m = money.Money(123, 'KRW')
>>> hash(m)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'Money'
```

`Money.__hash__` is set to `None`, and it disallows `Money` to be hashed.

`decimal.Decimal` is also hashable:

```pycon
>>> d = decimal.Decimal(123)
>>> hash(d)
123
```

So I think `__hash__` could be easily implemented e.g.:

```python
def __hash__(self):
    return hash((self.amount, self.currency))
```

**Comment by carlospalol** [comment]
Money objects are not immutable (e.g. you could do `m.amount += 1`). Offering a hash would hint they are immutable and then suitable to use as e.g. dictionary keys.

Tell me a bit more about your use case, maybe there is a need to make Money immutable.

**Comment by dahlia** [comment]
I hadn’t been aware of `Money` is mutable.  Is there any benefit of its mutability?

**Comment by carlospalol** [comment]
It's not mutable by design, it just uses regular attributes for `amount` and `currency`. Maybe you are right and it should be immutable...

**Comment by dahlia** [comment]
Python objects are mutable by default, and I believe there’s consensus among Python programmers that *if you write “it is immutable” in the docs you shouldn’t change its attributes.* Of course it would be better if you make these attributes read-only using `property`.

**Comment by carlospalol** [comment]
Money is now immutable by convention and hinted by using properties. Stay tuned for a new release soon.

**Comment by dahlia** [comment]
Cool!  Thank you!
