### ISSUE TITLE
Available backends?

### ISSUE THREAD

**Issue by jmagnusson** [carlospalol/money#16]
Can I find a list of this somewhere? Would be nice to have access to historical exchange rates.

**Comment by carlospalol** [comment]
There are no openly available backends that I know of yet. You may create one that uses external data (e.g. openexchangerates.org has historical data). Let me know how it worked out.

**Comment by jmagnusson** [comment]
Okay thanks. I kind of expected that. Just thought it would be a good idea to make this publicly available.
