### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by rvogel** [carlospalol/money#17]
Hi, I'm trying to use money into a GAE app.

For testing purposes, I've tried into the console and keep raising the same error. Here's a simple print from the console:
```
drwxr-xr-x   7 me  admin   238B 28 Mai 12:05 ./
drwxr-xr-x@ 14 me  admin   476B 28 Mai 12:02 ../
-rw-r--r--@  1 me  admin   6,0K 28 Mai 12:05 .DS_Store
-rw-r--r--@  1 me  admin     0B 28 Mai 10:57 __init__.py
drwxr-xr-x@ 19 me  admin   646B 28 Mai 12:06 babel/
drwxr-xr-x@  9 me  admin   306B 28 Mai 11:47 money/
drwxr-xr-x@  9 me  admin   306B 28 Mai 11:14 moneyed/
mymac:libs $ python
Python 2.7.9 (default, Apr  7 2015, 07:58:25) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import babel
>>> import money
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "money/__init__.py", line 5, in <module>
    from .money import Money, XMoney
  File "money/money.py", line 33
    "Decimal(): '{}'".format(amount)) from None
                                         ^
SyntaxError: invalid syntax
>>> 
```

Any guidance?

**Comment by rvogel** [comment]
Nevermind... I've used Python 3.x into 2.x.

**Comment by carlospalol** [comment]
Hi Rafael, thanks for sharing.

For anyone else getting this: when using the package source code directly, there are two source directories: `src` and `src-py2`. You need to use the appropriate one depending on your python version. If you install the package using setup.py, it will automatically install the right source, and you don't have to worry about this.
