### ISSUE TITLE
Subclassing `money.Money` with operators.

### ISSUE THREAD

**Issue by allonhadaya** [carlospalol/money#19]
```python
from money import Money

m = Money('0', 'BTC') + Money('0', 'BTC')
# BTC 0

class BTC(Money):
    def __init__(self, amount=0):
        super().__init__(amount=amount, currency='BTC')

m = BTC('0') + BTC('0')
```
crash
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../site-packages/money/money.py", line 119, in __add__
    return self.__class__(amount, self._currency)
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given
```
I would like to get the subclass instances to implement arithmetic, equality, and comparison operators.

 Do I have to implement all of the special methods and delegate a call using `super`, or is there an artificial limit to the current implementation?

**Comment by carlospalol** [comment]
Hi Allon, the example in the docs actually needs to be fixed. Followup at #20.

I think you would need something like this:

```python
class BTC(Money):
    def __init__(self, amount=0, currency='BTC'):
        if currency != 'BTC':
                raise ValueError('something')
        super().__init__(amount, currency)
```

**Comment by allonhadaya** [comment]
Aha, so the expression `self.__class__(amount, self._currency)` is creating a new instance of `BTC`, but `BTC.__init__` is not expecting the currency argument. I'll throw a suggestion your way on #20.
