### ISSUE TITLE
Remove ISO compliance check for currency

### ISSUE THREAD

**Issue by jbieler** [carlospalol/money#26]
I really like your library so far. Thank you for writing it!

There is however one problem, as I'm working with cryptocurrencies, that are not always compliant to the ISO currency standard. Can you remove the ISO check when creating currencies? Or can you make it configurable to be able to switch it off?

**Comment by carlospalol** [comment]
Thank you! I think it would be a good idea to let it optionally be non-ISO 4217. I will look into it.

**Comment by JamesMcGuigan** [comment]
As a temporary workaround fix, this will allow 3-4 letter currency including DOGE and MOON

**requirements.sh**
```
if [[ ! -d ./venv ]]; then
    python3 -m venv venv
fi
source venv/bin/activate
pip-compile
pip-sync
sed -i 's/^REGEX_CURRENCY_CODE = .*/REGEX_CURRENCY_CODE = re.compile("^[A-Z]{3,4}$")/' venv/lib/python*/site-packages/money/money.py
```

**Comment by jbieler** [comment]
Thanks for the answer! We also have found a similar fix to alter the reflex. As this is not an issue for me anymore, I’ll close the ticket.
