### ISSUE TITLE
Python 2.x permits comparison between Money and string

### ISSUE THREAD

**Issue by svisser** [carlospalol/money#9]
In Python 2.x you can compare numeric and non-numeric types. This means you can do:

```python
>>> Money('3', 'GBP') > '50'
False
```

which can lead to confusing situations (e.g., accidentally forgotten to deserialise the `'50'` to a numeric value). It seems to me that this situation should be rejected in Python 2.x. In Python 3.x the above leads to a `TypeError`:

```python
>>> Money('3', 'GBP') > '50'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/svisser/.virtualenvs/test3/lib/python3.4/site-packages/money/money.py", line 75, in __gt__
    return self.amount > other
TypeError: unorderable types: decimal.Decimal() > str()
```

**Comment by carlospalol** [comment]
Thanks for reporting this Simeon. After some pondering I'm actually deprecating the direct comparison between Money and non-Money objects in favor of an equally simple and more explicit `m.amount > 50`, with its "natural" Python quirks. 075c65817d339d9364724f124a2fc4b05d11e14c

Check out the note on the README: https://github.com/carlospalol/money#differences-between-python-versions
